- name: Install dependencies
  become: yes
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ dependency_packages }}"

- name: Add required repository for Ubuntu 14.04
  become: yes
  apt_repository:
    repo: "{{ item }}"
    update_cache: yes
  with_items: "{{ ubuntu_1404_apt_repo }}"

- name: Install Ubuntu 14.04 requirements
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ ubuntu_1404_dependencies }}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Link required verion of gcc/g++ for Ubuntu 14.04
  become: yes
  alternatives: name={{ item.name }} link={{ item.link }} path={{ item.path }}
  with_items:
    - { name: gcc, link: /usr/bin/gcc, path: /usr/bin/gcc-4.9 }
    - { name: g++, link: /usr/bin/g++, path: /usr/bin/g++-4.9 }
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Install Ubuntu 16.04 requirements
  become: yes
  apt:
    name: "{{ item }}"
  with_items: "{{ ubuntu_1604_dependencies }}"
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Create build directory
  file: 
    path: "{{ build_dir }}" 
    state: directory 

- name: Checkout protobuf repo
  git:
    repo: "{{ protobuf_repo }}"
    dest: "{{ build_dir }}/protobuf"
    version: "{{ protobuf_version }}"

- name: Build and install protobuf
  command: "{{ item }}"
  become: yes
  args:
    chdir: "{{ build_dir }}/protobuf"
  environment:
    CFLAGS: -Os
    CXXFLAGS: -Os
    LDFLAGS: -Wl,-s
  with_items:
    - ./autogen.sh
    - ./configure --prefix=/usr
    - make -j{{ num_cores }}
    - make install
    - ldconfig

- name: Checkout gRPC repo
  git:
    repo: "{{ grpc_repo }}"
    dest: "{{ build_dir }}/grpc"
    version: "{{ grpc_version }}"

- name: Build and install gRPC
  command: "{{ item }}"
  become: yes
  args:
    chdir: "{{ build_dir }}/grpc"
  environment:
    LDFLAGS: -Wl,-s
  with_items:
    - make -j{{ num_cores }}
    - make install
    - ldconfig

- name: Checkout BMv2 repo
  git:
    repo: "{{ bmv2_repo }}"
    dest: "{{ build_dir }}/bmv2"
    version: "{{ bmv2_version }}"

- name: Create temporary build directory for BMv2
  tempfile:
    path: "{{ build_dir }}/bmv2"
    state: directory
  register: bmv2_tempdir

- name: Install bmv2 dependencies
  command: "{{ item }}"
  become: yes
  args:
    chdir: "{{ bmv2_tempdir.path }}"
  with_items:
    - bash ../travis/install-thrift.sh
    - bash ../travis/install-nanomsg.sh
    - ldconfig
    - bash ../travis/install-nnpy.sh

- name: Delete bmv2 temporary build directory
  become: yes
  file:
    state: absent
    path: "{{ bmv2_tempdir.path }}"

- name: Checkout P4Runtime repo
  git:
    repo: "{{ p4runtime_repo }}"
    dest: "{{ build_dir }}/p4runtime"
    version: "{{ p4runtime_version }}"

- name: Build and install P4Runtime
  command: "{{ item }}"
  become: yes
  args:
    chdir: "{{ build_dir }}/p4runtime"
  with_items:
    - ./autogen.sh
    - ./configure --with-proto 'CXXFLAGS=-O0 -g'
    - make -j{{ num_cores }}
    - make install
    - ldconfig

- name: Build and install BMv2
  command: "{{ item }}"
  become: yes
  args:
    chdir: "{{ build_dir }}/bmv2"
  with_items:
    - ./autogen.sh
    - ./configure --enable-debugger --with-pi 'CXXFLAGS=-O0 -g'
    - make -j4
    - make install
    - ldconfig

- name: Build and install simple_switch_grpc target
  command: "{{ item }}"
  become: yes
  args:
    chdir: "{{ build_dir }}/bmv2/targets/simple_switch_grpc"
  with_items:
    - ./autogen.sh
    - ./configure 'CXXFLAGS=-O0 -g'
    - make -j4
    - make install
    - ldconfig

- name: Checkout p4c repo
  git:
    repo: "{{ p4c_repo }}"
    dest: "{{ build_dir }}/p4c"
    version: "{{ p4c_version }}"

- name: Create p4c build directory
  file:
    path: "{{ build_dir }}/p4c/build"
    state: directory

- name: Build and install p4c
  command: "{{ item }}"
  become: yes
  args:
    chdir: "{{ build_dir }}/p4c/build"
  with_items:
    - cmake ..
    - make -j4
    - make install
    - ldconfig
